# This Dockerfile adds a non-root user with sudo access
ARG ALPINE_VARIANT=3.11

FROM alpine:${ALPINE_VARIANT}
ARG HUGO_VERSION=0.76.3

ADD https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_Linux-ARM64.tar.gz /tmp

RUN tar -xf /tmp/hugo_${HUGO_VERSION}_Linux-ARM64.tar.gz -C /tmp \
    && mkdir -p /usr/local/sbin \
    && mv /tmp/hugo /usr/local/sbin/hugo \
    && rm -rf /tmp/hugo_${HUGO_VERSION}_linux_ARM64

#RUN apk update \
#    && apk upgrade \
#    && apk add --no-cache ca-certificates \
#    && rm -rf /var/cache/apk/*

CMD ["echo", "Hello from Hugo on ARM64"]